{
  "date": "2019-11-06",
  "count": 3,
  "cves": [
    {
      "cve_id": "CVE-2019-5010",
      "repo_info": "[JonathanWilbur/CVE-2019-5010](https://github.com/JonathanWilbur/CVE-2019-5010)",
      "description": "CVE-2019-5010 Exploit PoC - Python Denial of Service via Malformed X.509v3 Extension",
      "date": "2019-11-06",
      "raw_date": "2019-11-06T07:26:43Z"
    },
    {
      "cve_id": "CVE-2019-10475",
      "repo_info": "[vesche/CVE-2019-10475](https://github.com/vesche/CVE-2019-10475)",
      "description": "no description",
      "date": "2019-11-06",
      "raw_date": "2019-11-06T22:19:01Z"
    },
    {
      "cve_id": "CVE-2018-15982",
      "repo_info": "[create12138/CVE-2018-15982](https://github.com/create12138/CVE-2018-15982)",
      "description": "no description",
      "date": "2019-11-06",
      "raw_date": "2019-11-06T09:08:04Z"
    }
  ],
  "generated_at": "2025-10-07T01:12:47.087218",
  "metadata": {
    "total_cves": 3,
    "date_range": "2019-11-06",
    "source": "README.md",
    "script_version": "2.0"
  }
}